name: 2DRove CI workflow

on:
  # Replace with whatever branch you're working on :)
  push: 
    branches: 
      - mapgen
  pull_request:
    branches:
      - mapgen

jobs:
  runTests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      # Checkout repo code
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
      # Caches information to make future jobs go faster
      - name: Cache Library
        uses: actions/cache@v2
        with:
          path: Library
          key: Library
      # Runs tests using integrated Test Runner for workflows
      - name: Unity - Test runner
        uses: game-ci/unity-test-runner@v4.1.1
        # Need to generate Pro Unity license with Github secrets to get this to work   
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          projectPath: 2DRove
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          unityVersion: 2022.3.19f1
          testMode: playmode
          customParameters: -debugCodeOptimization -enableCodeCoverage -coverageResultsPath ./coverage-results -coverageOptions generateHtmlReport
      # Archive our code coverage results in a zip file (will try to output it to actions later)
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: 2DRove/CodeCoverage
            
